export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const INIT_ORDER = "INIT_ORDER";
export const INIT_PURCHASE = "INIT_PURCHASE";
export const SET_FETCHED_ORDERS = "SET_FETCHED_ORDERS";
